### ISSUE TITLE
Dividends

### ISSUE THREAD

**Issue by smart-law** [smart-law/LiquidRE#1]
https://github.com/meronym/dividends-paper/blob/master/dividends.pdf

https://medium.com/@weka/dividend-bearing-tokens-on-ethereum-42d01c710657

**Comment by smart-law** [comment]
https://github.com/pipermerriam/ethereum-alarm-governance/blob/1b4a9a0355976f92e88396582a64fdfb50bbe858/contracts/DividendDB.sol
https://github.com/pipermerriam/ethereum-alarm-governance/tree/1b4a9a0355976f92e88396582a64fdfb50bbe858/tests/dividends

https://github.com/ritave/Lunyr-Recuitment/blob/4d95e36a8e1ae119ee8e79d8a3a374e96ab9913d/contracts/Shareholders.sol

https://github.com/sandeepnailwal/maarifa/blob/a3640aaa67e67bf1604d7617e9b865a35f73c256/contracts/token.sol

**Comment by smart-law** [comment]
https://github.com/cryptectum/Smart-Contract/blob/2e058fdbb87a7f2d5edb8eff334803409795e45b/F_DividendInEthEnabledToken.sol

**Comment by smart-law** [comment]
https://github.com/NathanLewis/surefair/blob/4fbea61a39af5376038ecae75dc72b78e3a107ce/contracts/Insurance.sol

**Comment by smart-law** [comment]
`// dividend logic

  function dividendsOwing(address account) internal returns(uint) {
    var newDividendPoints = totalDividendPoints - accounts[account].lastDividendPoints;
    return (accounts[account].balance * newDividendPoints) / pointsMultiplier;
  }

  modifier updateDividendBalance(address account) {
    var owing = dividendsOwing(account);
    if(owing > 0) {
      unclaimedDividends = safeSub(unclaimedDividends, owing);
      accounts[account].dividendBalance = safeAdd(accounts[account].dividendBalance, owing);
      accounts[account].lastDividendPoints = totalDividendPoints;
    }
    _;
  }

  function disperse(uint amount) internal {
    totalDividendPoints += (amount * pointsMultiplier / totalSupply);
    unclaimedDividends += amount;
  }

  function updatePendingDispersal() internal {
    if(this.balance > lastDispersalBalance) {
      pendingDispersalBalance += this.balance - lastDispersalBalance;
    }
    lastDispersalBalance = this.balance;
  }

  function resetPendingDispersal() internal {
    pendingDispersalBalance = 0;
    lastDispersalBalance = this.balance;
  }

  function disperseFunds() {
    Auction(Auction).beneficiaryWithdraw();
    updatePendingDispersal();
    disperse(pendingDispersalBalance);
    resetPendingDispersal();
  }

  function withdrawDividends() updateDividendBalance(msg.sender) returns (bool) {
      updatePendingDispersal();
      var amount = accounts[msg.sender].dividendBalance;
      if (amount > 0) {
          accounts[msg.sender].dividendBalance = 0;
          if(!msg.sender.send(amount)) {
              accounts[msg.sender].dividendBalance = amount;
              return false;
          }
          DividendWithdrawal(msg.sender, amount);
      }
      return true;
  }
}`

**Comment by smart-law** [comment]
[dividends (1).pdf](https://github.com/smart-law/LiquidRE/files/1712587/dividends.1.pdf)

**Comment by meronym** [comment]
@smart-law Just saw that you're interested in implementing this dividend logic. Same here, wanna join forces? Write me at the e-mail address linked in the paper above.
